export const FETCH_DATA = "FETCH_DATA";
export const ADD_DATA = "ADD_DATA";
export const UPDATE_DATA = "UPDATE_DATA";
export const DELETE_DATA = "DELETE_DATA";

// Quản lý kho
export const FETCH_NHAPKHOTHUOC = "FETCH_NHAPKHOTHUOC";
export const DELETE_NHAPKHOTHUOC = "DELETE_NHAPKHOTHUOC";
export const CREATE_NHAPKHOTHUOC = "CREATE_NHAPKHOTHUOC";
export const EDIT_NHAPKHOTHUOC = "EDIT_NHAPKHOTHUOC";
export const UPDATE_NHAPKHOTHUOC = "UPDATE_NHAPKHOTHUOC";

// Quản lý nhà files
export const FETCH_FILES = "FETCH_FILES";
export const DELETE_FILES = "DELETE_FILES";
export const CREATE_FILES = "CREATE_FILES";
export const EDIT_FILES = "EDIT_FILES";
export const UPDATE_FILES = "UPDATE_FILES";

// Quản lý nhà cung cấp
export const FETCH_NHACUNGCAP = "FETCH_NHACUNGCAP";
export const DELETE_NHACUNGCAP = "DELETE_NHACUNGCAP";
export const CREATE_NHACUNGCAP = "CREATE_NHACUNGCAP";
export const EDIT_NHACUNGCAP = "EDIT_NHACUNGCAP";
export const UPDATE_NHACUNGCAP = "UPDATE_NHACUNGCAP";

// Quản lý thông tin khách hàng
export const FETCH_THONGTINKHACHHANG = "FETCH_THONGTINKHACHHANG";
export const DELETE_THONGTINKHACHHANG = "DELETE_THONGTINKHACHHANG";
export const CREATE_THONGTINKHACHHANG = "CREATE_THONGTINKHACHHANG";
export const EDIT_THONGTINKHACHHANG = "EDIT_THONGTINKHACHHANG";
export const UPDATE_THONGTINKHACHHANG = "UPDATE_THONGTINKHACHHANG";

// Quản lý bán hàng
export const FETCH_BANHANG = "FETCH_BANHANG";
export const DELETE_BANHANG = "DELETE_BANHANG";
export const CREATE_BANHANG = "CREATE_BANHANG";
export const EDIT_BANHANG = "EDIT_BANHANG";
export const UPDATE_BANHANG = "UPDATE_BANHANG";
export const ITEM_HOADON_BANHANG = "ITEM_HOADON_BANHANG";

// Quản lý hoá đơn đã hoàn thất
export const FETCH_HOADONDAHOANTAT = "FETCH_HOADONDAHOANTAT";
export const DELETE_HOADONDAHOANTAT = "DELETE_HOADONDAHOANTAT";
export const CREATE_HOADONDAHOANTAT = "CREATE_HOADONDAHOANTAT";
export const EDIT_HOADONDAHOANTAT = "EDIT_HOADONDAHOANTAT";
export const UPDATE_HOADONDAHOANTAT = "UPDATE_HOADONDAHOANTAT";

// Quản lý user
export const FETCH_TAIKHOAN = "FETCH_TAIKHOAN";
export const DELETE_TAIKHOAN = "DELETE_TAIKHOAN";
export const CREATE_TAIKHOAN = "CREATE_TAIKHOAN";
export const EDIT_TAIKHOAN = "EDIT_TAIKHOAN";
export const UPDATE_TAIKHOAN = "UPDATE_TAIKHOAN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

//Quan lý thông báo
export const FETCH_THONGBAO = "FETCH_THONGBAO";
export const DELETE_THONGBAO = "DELETE_THONGBAO";

//QuanLyCMND

export const FETCH_CMND = "FETCH_CMND";
export const CREATE_CMND = "CREATE_CMND";
export const DELETE_CMND = "DELETE_CMND";

//Quản lý áo quần

export const FETCH_KHO = "FETCH_KHO";
export const DELETE_KHO = "DELETE_KHO";
export const CREATE_KHO = "CREATE_KHO";
export const EDIT_KHO = "EDIT_KHO";
export const UPDATE_KHO = "UPDATE_KHO";
export const SEARCH_SANPHAM = "SEARCH_SANPHAM";

// sản phẩm được
export const FETCH_SANPHAMDUOC = "FETCH_SANPHAMDUOC";
export const DELETE_SANPHAMDUOC = "DELETE_SANPHAMDUOC";
export const CREATE_SANPHAMDUOC = "CREATE_SANPHAMDUOC";
export const EDIT_SANPHAMDUOC = "EDIT_SANPHAMDUOC";
export const UPDATE_SANPHAMDUOC = "UPDATE_SANPHAMDUOC";

// loại sản phẩm
export const FETCH_LOAISANPHAM = "FETCH_LOAISANPHAM";
export const DELETE_LOAISANPHAM = "DELETE_LOAISANPHAM";
export const CREATE_LOAISANPHAM = "CREATE_LOAISANPHAM";
export const EDIT_LOAISANPHAM = "EDIT_LOAISANPHAM";
export const UPDATE_LOAISANPHAM = "UPDATE_LOAISANPHAM";

// size
export const FETCH_SIZE = "FETCH_SIZE";
export const DELETE_SIZE = "DELETE_SIZE";
export const CREATE_SIZE = "CREATE_SIZE";
export const EDIT_SIZE = "EDIT_SIZE";
export const UPDATE_SIZE = "UPDATE_SIZE";

// giohang
export const FETCH_CART = "FETCH_CART";
export const DELETE_CART = "DELETE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const EDIT_CART = "EDIT_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const ORDER_CART = "ORDER_CART";
export const FETCH_ORDER = "FETCH_ORDER";

// message order
export const FETCH_MESSAGE_ORDER = "FETCH_MESSAGE_ORDER";
export const ADD_MESSAGE_ORDER = "ADD_MESSAGE_ORDER";
export const EDIT_MESSAGE_ORDER = "EDIT_MESSAGE_ORDER";
export const UPDATE_MESSAGE_ORDER = "UPDATE_MESSAGE_ORDER";
export const DELETE_MESSAGE_ORDER = "DELETE_MESSAGE_ORDER";

// sản phẩm đã xem
export const ADD_TO_PRODUCT_SAME = "ADD_TO_PRODUCT_SAME";
export const FETCH_PRODUCT_SAME = "FETCH_PRODUCT_SAME";

// comment khách hàng
export const FETCH_COMMENT_USER = "FETCH_COMMENT_USER";
export const ADD_COMMENT_USER = "ADD_COMMENT_USER";
export const DELETE_COMMENT_USER = "DELETE_COMMENT_USER";

// Thông tin đặt hàng
export const FETCH_THANH_PHO = "FETCH_THANH_PHO";
export const FETCH_QUAN = "FETCH_QUAN";
